export const POST_DATA_REQUEST = "POST_DATA_REQUEST";
export const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";
export const POST_DATA_FAILURE = "POST_DATA_FAILURE";
export const POST_COUNT_INCREMENT = "POST_COUNT_INCREMENT";
export const POST_COUNT_DECREMENT = "POST_COUNT_DECREMENT";
